env: prod
component: catalogue
params: "DOCUMENTDB:prod.catalogue.mongo,MONGOURL:prod.docdb.catalogue.url"

schemaLoadJob:
  create: true
  type: mongo

resources:
   limits:
     cpu: 300m
     memory: 350Mi
   requests:
     cpu: 200m
     memory: 256Mi